stages:
  - build
  - test
  - deploy

cypress_tests:
  image: debian:bullseye
  #is it enough to ensure clean up ?
  artifacts:
    - /root/.npm/_logs/*-debug.log
  after_script:
    - docker-compose down
  script:
    - |
      apt update
      apt full-upgrade -y 
      apt install -y docker.io docker-compose npm chromium
      apt install --fix-missing -y xvfb
    - docker-compose build
    - docker-compose up -d
    - |
      cd cypress
      npm install --production=false
      npm run test