stages:
  - build
  - test
  - deploy

cypress_tests:
  image: debian:bullseye
  #is it enough to ensure clean up ?
  artifacts:
    expire_in: 1 week
    paths:
      - /root/.npm/_logs/*-debug.log
  after_script:
    - docker-compose down
  script:
    - |
      apt update
      apt full-upgrade -y 
      apt install -y docker.io docker-compose npm chromium
      apt install --fix-missing -y xvfb
    - docker-compose build
    - docker-compose up -d
    - sleep 30
    - docker run -v $PWD/cypress:/e2e -w /e2e cypress/included:9.2.0