stages:
  - build
  - test
  - deploy

cypress_tests:
  image: debian:bullseye
  #is it enough to ensure clean up ?
  after_script:
    - docker-compose down
  script:
    - |
      apt update
      apt full-upgrade -y 
      apt install -y docker.io docker-compose npm chromium
      apt install --fix-missing -y xvfb
    - docker-compose build
    - docker-compose up -d
    - |
      docker ps -a
      cd cypress
      npm install 
      npm run cypress run --headless