stages:
  - build
  - test
  - deploy

cypress_tests:
#  image:
#    name: cypress/included:9.2.0
#    entrypoint: ["/bin/sh", "-c"]
  image: debian:bullseye
  #is it enough to ensure clean up ?
  artifacts:
    expire_in: 1 week
    paths:
      - /root/.npm/_logs/*-debug.log
      - cypress/screenshots
      - cypress/videos
  after_script:
    - docker-compose down
  script:
    - |
      apt update
      apt full-upgrade -y 
      apt install -y docker.io docker-compose npm chromium
      apt install --fix-missing -y xvfb
    - docker-compose build
    - docker-compose up -d
    - sleep 30
    - |
      cd cypress
      npm ci 
      npm run test
