stages:
  - build
  - test
  - deploy

# local test on dev machine (linux + docker + gitlab-runner installed) can be run with:
# gitlab-runner exec docker --docker-volumes  /run/docker.sock:/run/docker.sock e2e_tests
e2e_tests:
  image: docker/compose:1.29.2
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts/screenshots
      - artifacts/videos
      - artifacts/logs
  after_script:
    # this is after_script to execute even when the job fails
    # recover artifacts produced by the e2e container and make them available
    # || true to force success of step even if the src does not exist
    # en ensure the docker-compose down step is reached and executed
    - docker cp e2e:/e2e/cypress/videos artifacts/ || true
    - docker cp e2e:/e2e/cypress/screenshots artifacts/ || true
    - docker cp e2e:/root/.npm/_logs/ artifacts/logs/ || true
    - docker-compose down  || true
  script:
    - mkdir -p artifacts/screenshots artifacts/videos artifacts/logs
    - docker-compose build
    - docker-compose up --force-recreate --exit-code-from e2e
