stages:
  - build
  - test
  - deploy

cypress_tests:
#  image:
#    name: cypress/included:9.2.0
#    entrypoint: ["/bin/sh", "-c"]
  image: debian:bullseye
  #is it enough to ensure clean up ?
  artifacts:
    expire_in: 1 week
    paths:
      - /root/.npm/_logs
      - cypress/screenshots
      - cypress/videos
  after_script:
    - docker-compose down
  script:
    - |
      apk add docker.io docker-compose
    - docker-compose build
    - docker-compose up -d
    # yes there are better ways to wait for all the containers to be ready. this will do for now
    - sleep 30
    - docker-compose exec -w /e2e dcc ./cypress-setup.sh
