stages:
  - build
  - test
  - deploy

cypress_tests:
  image: debian:bullseye
  artifacts:
    expire_in: 1 week
    paths:
      - cypress/cypress/screenshots
      - cypress/cypress/videos
  after_script:
    - docker-compose down  || true
  script:
    - apt update
    - apt install -y docker.io docker-compose
    - docker-compose build
    - docker-compose up --force-recreate --exit-code-from e2e

e2e_tests:
  image: docker/compose:1.29.2
  after_script:
    - docker-compose exec -T -w e2e e2e ls -lR cypress/screenshots cypress/videos || true
    - ls -lR artifacts
    - docker-compose down  || true
  script:
    - mkdir -p artifacts/screenshots artifacts/videos artifacts/logs
    - pwd
    - ls -l artifacts
    - docker-compose build
    - docker-compose up --force-recreate --exit-code-from e2e
