stages:
  - build
  - test
  - deploy

cypress_tests:
  image: debian:bullseye
  artifacts:
    expire_in: 1 week
    paths:
      - cypress/cypress/screenshots
      - cypress/cypress/videos
  after_script:
    - docker-compose down  || true
  script:
    - apt update
    - apt install -y docker.io docker-compose
    - docker-compose build
    - docker-compose up -d
    # yes there are better ways to wait for all the containers to be ready. this will do for now
    - sleep 30
    - docker-compose exec  -T -w /e2e dcc ./cypress-setup.sh
