stages:
  - build
  - test
  - deploy

cypress_tests:
  image: debian:bullseye
  artifacts:
    expire_in: 1 week
    paths:
      - cypress/cypress/screenshots
      - cypress/cypress/videos
  after_script:
    - docker-compose down  || true
  script:
    - apt update
    - apt install -y docker.io docker-compose
    - docker-compose build
    - docker-compose up --force-recreate --exit-code-from e2e
