version: "3.7"

services:

  mariadb:
    init: true
    container_name: mariadb
    build:
      context: docker/mariadb
      args:
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        MARIADB_USER2: ${MARIADB_USER2}
        MARIADB_PASSWORD2: ${MARIADB_PASSWORD2}
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER2: ${MARIADB_USER2}
      MARIADB_PASSWORD2: ${MARIADB_PASSWORD2}
    ports:
      - 3306:3306

  dcc:
    init: true
    container_name: dcc
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        MARIADB_USER2: ${MARIADB_USER2}
        MARIADB_PASSWORD2: ${MARIADB_PASSWORD2}
        IP: ${IP}
        HOSTNAME: ${HOSTNAME}
        DOMAIN: ${DOMAIN}
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER2: ${MARIADB_USER2}
      MARIADB_PASSWORD2: ${MARIADB_PASSWORD2}
      IP: ${IP}
      HOSTNAME: ${HOSTNAME}
      DOMAIN: ${DOMAIN}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - "mariadb"

