version: "3.7"

services:
  ldap_server:
    build:
      context: .
      dockerfile: ldap_server/Dockerfile
      args:
        LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
        LDAP_BASE_DN: ${LDAP_BASE_DN}
        LDAP_ORGANISATION: ${LDAP_ORGANISATION}
        LDAP_DOMAIN: ${LDAP_DOMAIN}
    environment:
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
    command: [ "--loglevel", "debug" ]
    ports:
      - 389:389

  ldap_admin:
    image: osixia/phpldapadmin
    ports:
      - 8090:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
      PHPLDAPADMIN_HTTPS: 'false'


  mariadb:
    init: true
    container_name: mariadb
    build:
      context: docker/mariadb
      args:
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        MARIADB_USER2: ${MARIADB_USER2}
        MARIADB_PASSWORD2: ${MARIADB_PASSWORD2}
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER2: ${MARIADB_USER2}
      MARIADB_PASSWORD2: ${MARIADB_PASSWORD2}
    ports:
      - 3306:3306

  dcc:
    init: true
    container_name: dcc
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        MARIADB_USER2: ${MARIADB_USER2}
        MARIADB_PASSWORD2: ${MARIADB_PASSWORD2}
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER2: ${MARIADB_USER2}
      MARIADB_PASSWORD2: ${MARIADB_PASSWORD2}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - "mariadb"

  mailhog:
    # fake smtp server to receive all email traffic and test notifications.
    init: true
    container_name: mailhog
    image: mailhog/mailhog
    command: ["-smtp-bind-addr", "0.0.0.0:25"]
    user: root
    expose:
      - 25
      - 8025
    ports:
      - 8025:8025
    healthcheck:
      test: echo | telnet 127.0.0.1 25
    depends_on:
      - "mariadb"
      - "dcc"

  e2e:
    build:
      context: .
      dockerfile: docker/e2e/Dockerfile
    init: true
    container_name: e2e
    working_dir: /e2e
    #command: [ "/bin/sleep", "1h"]
    depends_on:
      - "mariadb"
      - "dcc"
      - "mailhog"