#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2007 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "AuthorSQL.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";


$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

%params = $query -> Vars;

my $AuthorGroup = $params{authorgroupid} || 0;


if ($AuthorGroup > 0) {
    GetAuthorsByAuthorGroup ($AuthorGroup);
} else {
    GetAuthors();
}

print $query -> header( -charset => $HTTP_ENCODING );
if ($AuthorGroup > 0) {
  FetchAuthorGroup($AuthorGroup);
  DocDBHeader("List of Authors in ".$AuthorGroups{$AuthorGroup}{AuthorGroupName},"",-scripts => ["serverstatus", "PopUps"]);
} else {
  DocDBHeader("List of Authors","",-scripts => ["serverstatus", "PopUps"]);
}

unless ($AuthorGroup) {
   print "<h3>All Existing Authors";
   unless ($Public) {
      print " (<a href=\"$AuthorAddForm\">Add</a> a new author)";
   }
   print "</h3>\n";
}

AuthorsTable();

DocDBNavBar();
DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
