#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

# Copyright 2001-2007 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CGI;
use DBI;

require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "SecuritySQL.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";
require "MiscSQL.pm";
require "FSUtilities.pm";
require "HTMLUtilities.pm";
require "Security.pm";
require "SQLChecks.pm";

require "RevisionHTML.pm";

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

my $DocumentID = $params{docid};
   $DocumentID =~ s/^\s+//; # Remove leading and trailing spaces
   $DocumentID =~ s/\s+$//;
my $Version    = $params{version};
my $AsOf       = $params{asof};
my $FileName   = $params{filename};
my $Extension  = $params{extension};

unless ($DocumentID) {
  push @ErrorStack,"You are must supply a document number!";
}  

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

GetSecurityGroups();

# Roy Williams Sept 2012 allows DocAlias as well as DocID
if ($DocumentID =~ m/^\d+$/) {
   FetchDocument($DocumentID);
} elsif ($DocumentID =~ m/^[a-zA-Z]\d{6,8}$/) {
   my $DocAlias = $DocumentID;
   $DocumentID = GetDocumentIDByAlias($DocAlias);
   $DocumentID = int($DocumentID);
   FetchDocument($DocumentID);
} else {
   my $junk = HTML::Entities::encode($DocumentID);
   push @ErrorStack,"Invalid document ID: '$junk'";
}



#FetchDocument($DocumentID);

if (defined $Version && defined $AsOf) {
  push @ErrorStack,"You may not specify both a version and date.";
}
if (grep /\//,$FileName) {
  push @ErrorStack,"File names with / are not allowed for security reasons.";
}  

if (@ErrorStack) {  # The user made one or more mistakes, warn and exit
  print $query -> header( -charset => $HTTP_ENCODING );
  DocDBHeader("File Retrieve Results"); 
  EndPage();
}

my $DocRevID;
if (defined $Version) {
  if ($Version eq "") { # Prob can't happen now, but may in future
    $Version = $Documents{$DocumentID}{NVersions};
  }
  $DocRevID = &FetchRevisionByDocumentAndVersion($DocumentID,$Version);
} elsif (defined $AsOf) {
  if (&CheckSQLDate($AsOf)) {
    $DocRevID = &FetchRevisionByDocumentAndDate($DocumentID,$AsOf);
    $Version  = $DocRevisions{$DocRevID}{VERSION};
  } else {
    push @ErrorStack,"The as-of date must be specifed in the form YYYY-MM-DD.";
  }
} else {
#  $Version = $Documents{$DocumentID}{NVersions};
  $Version = LastAccess($DocumentID);

  $DocRevID = &FetchRevisionByDocumentAndVersion($DocumentID,$Version);
}

unless (&CanAccess($DocumentID,$Version)) {
  if (&remote_user) {
    $user_name = &remote_user;
    push @ErrorStack,"The $user_name group is not authorized to view this document (or it does not exist).";
  } else {
    push @ErrorStack,"This document is not publicly accessible.";
  }  
}  

unless ($DocRevID) {
  push @ErrorStack,"This document does not exist.";
}

if (@ErrorStack) {  # The user made one or more mistakes, warn and exit
  print $query -> header( -charset => $HTTP_ENCODING );
  &DocDBHeader("File Retrieve Results"); 
  EndPage();
}

if ($FileName) {
  $FullFile = &FullFile($DocumentID,$Version,$FileName);
  $FullURL = &GetURLDir($DocumentID,$Version).CGI::escape($FileName);
} elsif ($Extension) {
  &FetchDocFiles($DocRevID);
  my $NFiles = 0;
  my $LastFile = "";
  foreach my $DocFileID (keys %DocFiles) {
    if ($DocFiles{$DocFileID}{DOCREVID} == $DocRevID &&
        grep /$Extension$/i,$DocFiles{$DocFileID}{NAME}) {
      ++$NFiles;
      $LastFile = $DocFiles{$DocFileID}{NAME};
    } 
  }
  if ($NFiles == 1) {
    $FullFile = &FullFile($DocumentID,$Version,$LastFile);
    $FullURL  = &GetURLDir($DocumentID,$Version).CGI::escape($LastFile);
  } elsif ($NFiles > 1) {
    push @WarnStack,"More than one file was found. Please select one below.";
  }  
} else {
  &FetchDocFiles($DocRevID);
  my $NFiles = 0;
  my $LastFile = "";
  foreach my $DocFileID (keys %DocFiles) {
    if ($DocFiles{$DocFileID}{DOCREVID} == $DocRevID &&
        $DocFiles{$DocFileID}{ROOT}) {
      ++$NFiles;
      $LastFile = $DocFiles{$DocFileID}{NAME};
    } 
  }
  if ($NFiles == 1) {
    $FullFile = &FullFile($DocumentID,$Version,$LastFile);
    $FullURL = &GetURLDir($DocumentID,$Version).CGI::escape($LastFile);
  } elsif ($NFiles > 1) {
    push @WarnStack,"More than one file was found. Please select one below.";
  } else {
    push @WarnStack,"No files were found. Document info is below.";
  }  
}    

unless (-e $FullFile) {
  push @WarnStack,"No appropriate file was found.";
}

# Removed call to FileUtilities.pm::StreamFile,
# I am also removing the function StreamFile
# to remove the dependency on perl::File::MimeInfo
# Phil Ehrens 10-30-2012

if ($FullURL) {
  print $query -> redirect(-location => $FullURL, -method => 'GET');
} else {
  print $query -> header( -charset => $HTTP_ENCODING );
  DocDBHeader("File Retrieve Results"); 
  EndPage(@ErrorStack);

  PrintRevisionInfo($DocRevID);

  DocDBNavBar();
  DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
}
