#!/bin/bash 

REPLICAS=(dcc-backup.ligo.org dcc-llo.ligo.org dcc-lho.ligo.org) 
MYSQL_QUERY="select UNIX_TIMESTAMP(TimeStamp), Alias  from dcc_docdb.Document order by TimeStamp desc  limit 1;"
FILESYSTEM_QUERY="find /usr1/www/html/DocDB/ -maxdepth 1 -name '0???'  -printf '%Ts\t%p\n' | sort -n | tail -n 1"

# 1 day plus 1 hour for replication time, happens to be 90,000 sec
GRACE_PERIOD="25 hours ago"
OLDEST_ACCEPTABLE=$(date -d "$GRACE_PERIOD" '+%s')
OLDIFS=$IFS
CHECK_STATUS=0

for REMOTE in ${REPLICAS[@]}
do
  IFS=$'\t'
  LAST_REMOTE_MYSQL=($(ssh $REMOTE "mysql -NB -e '$MYSQL_QUERY' 2>/dev/null"))
  if (( $? > 0 ))  ; then 
     CHECK_STATUS=2
     echo "    $REMOTE: could not query mysql"
  else
     if (( ${LAST_REMOTE_MYSQL[0]} < $OLDEST_ACCEPTABLE )) ; then 
         CHECK_STATUS=2
         echo "    $REMOTE: mysql is more than 1 day away from dcc.ligo.org"
     else
         echo "    $REMOTE: mysql is in sync"
     fi
  fi

  LAST_REMOTE_FILESYSTEM=($(ssh $REMOTE "$FILESYSTEM_QUERY") )
  if (( $? >0 )) ; then 
     echo "    $REMOTE: could not query filesystem"
  else
     if (( ${LAST_REMOTE_FILESYSTEM[0]} < $OLDEST_ACCEPTABLE )) ; then 
         CHECK_STATUS=2
         echo "    $REMOTE: filesystem is more than 1 day away from dcc.ligo.org"
     else
         echo "    $REMOTE: filesystem is in sync"
     fi
  fi 
  IFS=$OLD_IFS
done
exit $CHECK_STATUSST_LOCAL_MYSQL
